### ISSUE TITLE
display times / current availability for programs

### ISSUE THREAD

**Issue by jmlev** [codeforboston/need-now#13]
Options will be either open, closed, or something like "see details" (any ideas on language?).

**Comment by jmlev** [comment]
Maybe this is obvious to others (but it just occurred to me)-- I think the results should display (separately) both the dynamic open / closed / see more, and a static print-out of the program hours. The latter is still important for users to be able to know regardless of what the current situation is.

**Comment by kent37** [comment]
Proposal: To find Open/Closed status, parse the Days field in Javascript as follows:
- If the Days is unspecified, status is Unsure
- Split Days on semi-colons
- If none of the split fields contains the current day, status is Closed
- If one of the fields is the current day only, then the status is Open
- If one of the fields is the current day with additional data,
  - Split the field on the first space
  - If the second field has a dash,
    - split on the dash and try to parse the two fields as times
    - if the parse is successful, then the facility is Open between the given hours, otherwise Closed
  - If the second field has no dash, or the parse does not succeed, status is See Details
